- name: Restart Azure VM
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
    - name: Restart virtual machine
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group }}"
        name: "{{ vm_name }}"
        restarted: yes
      register: result

    - copy:
        content: "{{ result }}"
        dest: "qtorque_outputs.json"
