- name: Start Azure VM
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection
  tasks:
    - name: Start virtual machine
      azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ name }}"
        started: yes
      register: result

    - copy:
        content: "{{ result }}"
        dest: "qtorque_outputs.json"
